version: "3"
services:
  # global entrypoint
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - node-app
      - flask-app
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  # node app api server
  node-app:
    image: nodeapp
    container_name: node_app
    build:
      context: ./nodeapp
    restart: on-failure
  # flask app api server
  flask-app:
    image: flaskapp
    container_name: flask_app
    build:
      context: ./flaskapp
    restart: on-failure
